# Generated by Django 4.0 on 2021-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pic',
            new_name='profilepic',
        ),
        migrations.AddField(
            model_name='account',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
