# Generated by Django 4.0 on 2021-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilepic',
            field=models.ImageField(blank=True, default='images/user3.png', null=True, upload_to='documents'),
        ),
    ]
