# Generated by Django 4.0 on 2021-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilepic',
            field=models.ImageField(blank=True, default='accounts/static/images/user3.png', null=True, upload_to='documents'),
        ),
    ]
