# Generated by Django 4.0 on 2021-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student')], max_length=20),
        ),
    ]
