# Generated by Django 4.0 on 2021-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default='accounts/static/assets/images/blog/blog02.jpg', null=True, upload_to='poster'),
        ),
    ]
