# Generated by Django 4.0 on 2021-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_liveevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
