# Generated by Django 4.0 on 2021-12-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_liveevent_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveevent',
            name='user',
        ),
    ]
